scopes:
  - name: "Imperial Year 2"
    root: "~/OneDrive/0 Rong/00 Imperial/0 Year 2"
    folders:
      - "Corporate Finance and Capital Markets"
      - "Econometrics 1"
      - "Machine Learning"
      - "Microeconomics 2"
      - "Operations Research"
      - "z_Admin"

